services:
  grsso:
    build: .
    ports:
      - "9090:9090"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: grsso
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMTP_MAIL_USERNAME: ${SMTP_MAIL_USERNAME}
      SMTP_MAIL_PASSWORD: ${SMTP_MAIL_PASSWORD}
      OAUTH2_GOOGLE_CLIENT_ID: ${OAUTH2_GOOGLE_CLIENT_ID}
      OAUTH2_GOOGLE_CLIENT_SECRET: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      GEOIP_DATABASE_PATH: /app/geoip/dbip-city-lite.mmdb
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      geoip:
        condition: service_healthy
    volumes:
      - geoip-data:/app/geoip:ro
    networks:
      - grsso-net

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: grsso
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - grsso-net

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - grsso-net

  geoip:
    build: ./geoip
    healthcheck:
      test: ["CMD", "test", "-f", "/data/dbip-city-lite.mmdb"]
      interval: 5s
      retries: 20
    environment:
      GEOIP_DATA_DIR: /data
    volumes:
      - geoip-data:/data
    networks:
      - grsso-net

  webdav:
    image: bytemark/webdav:2.4
    container_name: myapp-webdav
    restart: unless-stopped

    environment:
      AUTH_TYPE: Basic
      USERNAME: ${WEB_DAV_USERNAME}
      PASSWORD: ${WEB_DAVE_PASSWORD}
      LOCATION: /webdav

    ports:
      - "8081:80"

    volumes:
      - webdav_data:/var/lib/dav

volumes:
  postgres-data:
  redis-data:
  geoip-data:
  webdav_data:

networks:
  grsso-net: