logging:
  level:
    root: INFO

    gr.grodov.grsso: DEBUG

    org.springframework.security: INFO
    org.springframework.web.client: INFO
    org.springframework.security.oauth2: INFO

    org.apache.tomcat.util.net.NioEndpoint: ERROR
    sun.rmi: ERROR
    java.io: ERROR
    javax.management: ERROR

server:
  port: 9090
  servlet:
    session:
      cookie:
        secure: false
        name: SSO_SESSION
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never