spring:
  application:
    name: gr-sso

  datasource:
    url: jdbc:postgresql://localhost:5432/gr-sso-db
    username: postgres
    password: brbawwjp239606!

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 129564153904-ktqcclfcffjtakulipm66b7od0raja86.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - email

#          github:
#            client-id: Ov23liY8BTn2x3lWqgm3
#            client-secret: fd19ae7bdd01fe42a79abc32463f3d6c68ae9930
#            scope:
#              - openid
#              - read:user
#              - user:email

      authorizationserver:
        issuer: http://localhost:9090
        client:
          crm-client:
            registration:
              client-id: crm-client
              client-secret: b4efd0df-04fa-4fca-8a78-ee0a8c89cd5d
              client-authentication-methods: client_secret_basic
              authorization-grant-types: authorization_code
              redirect-uris: http://127.0.0.1:8080/login/oauth2/code/grsso
              scopes:
                - openid

logging:
  level:
    root: DEBUG
    org.apache.tomcat.util.net.NioEndpoint: ERROR
    sun.rmi: ERROR
    java.io: ERROR
    javax.management: ERROR
    org.springframework.security: TRACE
    org.springframework.web.client: TRACE
    org.springframework.security.oauth2: TRACE

server:
  port: 9090
  servlet:
    session:
      cookie:
        secure: false
  error: #TODO Сделать env для разработки и прода
    include-stacktrace: never
    include-message: never
    include-binding-errors: never


grsso:
  front-url: http://localhost:5173